# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70251469e495201007b9b77c68e942f88b02e159ac4a28e7bfdf41599c924fee9d7462eef77d0ba153033638a28fd96fc917fae23e9c00274cdb604f163ed594

test:
  secret_key_base: b208f422e4c5f69abf4174294594aea21b4c5426e683685b1a953799a8353408dd87b180108c8d6334dea26887cab1f98baa3e57517c8a7f18eb670bcda01328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
